Pull Request with Current Website Code
4533-phoenix/website pull request #1
Opened 2018-01-25 23:58 UTC by OriginalName2

Making a pull request with current website code finished. Planning to add a lot more information to contacts and team/robot once I get more info on the topic. Will add more images later on when I get them.

2018-01-26 01:38 UTC, abrightwell requested changes
Some items that need to be addressed:

1). Move the CSS into a seperate `.css` file and link to it appropriately. Therefore you are not copy pasting and changes to style only need to happen in one place. 

2). Give each file an appropriate file extension.

2018-01-26 23:29 UTC, OriginalName2 commented
I've made requested changes with the files in the repository, 19 commits

2018-01-29 17:12 UTC, abrightwell requested changes
It's getting there, but need to fix the location of the stylesheet links as well, let's format the files with appropriate spacing and indentation.

2018-01-29 17:12 UTC, abrightwell commented on contacts.html
> +
This should be under `<header>`. Fix throughout.

2018-07-16 15:42 UTC, closed without merging